name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the frontend image (Angular)
      - name: Build Angular frontend
        run: |
          docker build -t frontend-app:latest ./Knowledge-Repository-UI

      # Build the backend image (Django)
      - name: Build Django backend
        run: |
          docker build -t backend-app:latest ./Backend

      # Start services using Docker Compose
      - name: Start services with Docker Compose
        run: |
          docker compose up -d
