name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build the frontend image (Angular)
      - name: Build Angular frontend
        run: |
          docker build -t frontend-app:latest ./frontend

      # Build the backend image (Django)
      - name: Build Django backend
        run: |
          docker build -t backend-app:latest ./backend

      # Start services using Docker Compose
      - name: Start services with Docker Compose
        run: |
          docker-compose up -d
